// Google Ads language constants - https://developers.google.com/google-ads/api/data/codes-formats
// Form stores/sends ID only.

export const GOOGLE_LANGUAGE_CONSTANTS = [
  { id: "1000", name: "English" },
  { id: "1001", name: "German" },
  { id: "1002", name: "French" },
  { id: "1003", name: "Spanish" },
  { id: "1004", name: "Italian" },
  { id: "1005", name: "Japanese" },
  { id: "1009", name: "Danish" },
  { id: "1010", name: "Dutch" },
  { id: "1011", name: "Finnish" },
  { id: "1012", name: "Korean" },
  { id: "1013", name: "Norwegian" },
  { id: "1014", name: "Portuguese" },
  { id: "1015", name: "Swedish" },
  { id: "1017", name: "Chinese (Simplified)" },
  { id: "1018", name: "Chinese (Traditional)" },
  { id: "1019", name: "Arabic" },
  { id: "1020", name: "Bulgarian" },
  { id: "1021", name: "Czech" },
  { id: "1022", name: "Greek" },
  { id: "1023", name: "Hindi" },
  { id: "1024", name: "Hungarian" },
  { id: "1025", name: "Indonesian" },
  { id: "1026", name: "Icelandic" },
  { id: "1027", name: "Hebrew" },
  { id: "1028", name: "Latvian" },
  { id: "1029", name: "Lithuanian" },
  { id: "1030", name: "Polish" },
  { id: "1031", name: "Russian" },
  { id: "1032", name: "Romanian" },
  { id: "1033", name: "Slovak" },
  { id: "1034", name: "Slovenian" },
  { id: "1035", name: "Serbian" },
  { id: "1036", name: "Ukrainian" },
  { id: "1037", name: "Turkish" },
  { id: "1038", name: "Catalan" },
  { id: "1039", name: "Croatian" },
  { id: "1040", name: "Vietnamese" },
  { id: "1041", name: "Urdu" },
  { id: "1042", name: "Filipino" },
  { id: "1043", name: "Estonian" },
  { id: "1044", name: "Thai" },
  { id: "1056", name: "Bengali" },
  { id: "1064", name: "Persian" },
  { id: "1072", name: "Gujarati" },
  { id: "1086", name: "Kannada" },
  { id: "1098", name: "Malayalam" },
  { id: "1101", name: "Marathi" },
  { id: "1102", name: "Malay" },
  { id: "1110", name: "Punjabi" },
  { id: "1130", name: "Tamil" },
  { id: "1131", name: "Telugu" },
] as const;

export type GoogleLanguageConstant = (typeof GOOGLE_LANGUAGE_CONSTANTS)[number];
